---
- name: Detect NVIDIA GPU
  command: lspci
  register: lspci_output
  changed_when: false
  when: not is_vagrant | default(false)

- name: Set fact if NVIDIA GPU is present
  set_fact:
    nvidia_gpu_present: "{{ 'NVIDIA' in lspci_output.stdout }}"
  when: not is_vagrant | default(false)

- name: NVIDIA Setup Block
  when:
    - not is_vagrant | default(false)
    - nvidia_gpu_present | default(false)
  block:

    - name: Install EPEL
      dnf:
        name: epel-release
        state: present

    - name: Install kernel headers and dev tools
      dnf:
        name:
          - kernel-devel
          - kernel-headers
          - gcc
          - make
          - dkms
        state: present

    - name: Install RPMFusion repo
      dnf:
        name: https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm
        state: present

    - name: Install NVIDIA driver packages
      dnf:
        name:
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda
        state: present

    - name: Add NVIDIA Container Toolkit repo
      get_url:
        url: https://nvidia.github.io/libnvidia-container/centos9/libnvidia-container.repo
        dest: /etc/yum.repos.d/libnvidia-container.repo

    - name: Install NVIDIA Container Toolkit
      dnf:
        name: nvidia-container-toolkit
        state: present

    - name: Configure Podman to use NVIDIA runtime
      copy:
        dest: /etc/containers/containers.conf.d/nvidia.conf
        content: |
          [engine]
          runtime = "nvidia"

    - name: Trigger reboot to load NVIDIA drivers
      reboot:
        msg: "Rebooting to activate NVIDIA drivers"
        connect_timeout: 5
        reboot_timeout: 600
