---
- name: Detect NVIDIA GPU
  command: lspci
  register: lspci_output
  changed_when: false
  when: not is_vagrant | default(false)

- name: Set fact if NVIDIA GPU is present
  set_fact:
    nvidia_gpu_present: "{{ 'NVIDIA' in lspci_output.stdout }}"
  when: not is_vagrant | default(false)

- name: NVIDIA Setup Block
  when:
    - not is_vagrant | default(false)
    - nvidia_gpu_present | default(false)
  block:

    - name: Disable nouveau kernel module
      ansible.builtin.copy:
        dest: /etc/modprobe.d/blacklist-nouveau.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          blacklist nouveau
          options nouveau modeset=0
      become: true
      notify: Rebuild initramfs after nouveau blacklist

    - name: Attempt to unload nouveau module (best effort)
      ansible.builtin.command: modprobe -r nouveau
      register: nouveau_remove
      changed_when: nouveau_remove.rc == 0
      failed_when: nouveau_remove.rc not in [0, 1]
      become: true
      ignore_errors: true

    - name: Install kernel headers and dev tools
      dnf:
        name:
          - kernel-devel
          - kernel-headers
          - gcc
          - make
          # - dkms
        state: present

    - name: Import EPEL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

    - name: Install EPEL
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ nvidia_repo_el_version }}.noarch.rpm"
        state: present

    - name: Import RPMFusion free GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-el-{{ ansible_distribution_major_version }}"

    - name: Import RPMFusion nonfree GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-el-{{ ansible_distribution_major_version }}"

    - name: Install RPMFusion free repo
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Install RPMFusion nonfree repo
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Install NVIDIA driver packages
      dnf:
        name:
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda
        state: present

    - name: Add NVIDIA Container Toolkit repo
      get_url:
        url: "{{ nvidia_container_repo_url }}"
        dest: /etc/yum.repos.d/libnvidia-container.repo

    - name: Install NVIDIA Container Toolkit
      dnf:
        name: nvidia-container-toolkit
        state: present

    - name: Configure Podman to use NVIDIA runtime
      copy:
        dest: /etc/containers/containers.conf.d/nvidia.conf
        content: |
          [engine]
          runtime = "nvidia"

    # - name: Trigger reboot to load NVIDIA drivers
    #   reboot:
    #     msg: "Rebooting to activate NVIDIA drivers"
    #     connect_timeout: 5
    #     reboot_timeout: 600
